spring:
    application:
        name: dataimp-service
    profiles:
      active: dev
    jackson:
        serialization.write_dates_as_timestamps: true
    mvc:
        favicon:
            enabled: false